import { Plan } from '@/types/plan';

export const MOCK_PLANS: Plan[] = [
  {
    id: '1',
    activity: 'Fútbol en Palermo',
    description: 'Partido 5vs5, ¡nos falta uno!',
    category: 'sport',
    coordinate: {
      latitude: -34.572,
      longitude: -58.425,
    },
    location_latitude: -34.572,
    location_longitude: -58.425,
    age_range_min: 18,
    age_range_max: 99,
    capacity: 10,
    participantCount: 9,
    duration: 60,
    gender_preference: 'any',
    is_flexible: false,
    location_name: 'Canchas de Palermo',
    location_address: 'Av. del Libertador 3000, CABA',
    visibility: 'Público',
    when: 'Hoy',
  },
  {
    id: '2',
    activity: 'Café por Villa Crespo',
    description: 'Charla y un buen café para cortar la tarde.',
    category: 'social',
    coordinate: {
      latitude: -34.59,
      longitude: -58.445,
    },
    location_latitude: -34.59,
    location_longitude: -58.445,
    age_range_min: 25,
    age_range_max: 40,
    capacity: 4,
    participantCount: 1,
    duration: 45,
    gender_preference: 'any',
    is_flexible: true,
    location_name: 'Café Crespin',
    location_address: 'Vera 699, CABA',
    visibility: 'Público',
    when: 'Ahora',
  },
  {
    id: '3',
    activity: 'Cine en Recoleta',
    description: 'Vemos los estrenos de la semana.',
    category: 'culture',
    coordinate: {
      latitude: -34.588,
      longitude: -58.395,
    },
    location_latitude: -34.588,
    location_longitude: -58.395,
    age_range_min: 20,
    age_range_max: 35,
    capacity: 6,
    participantCount: 3,
    duration: 120,
    gender_preference: 'any',
    is_flexible: false,
    location_name: 'Cine Recoleta',
    location_address: 'Vicente López 2050, CABA',
    visibility: 'Público',
    when: 'Hoy',
  },
];